### ISSUE TITLE
Role name is included in playbook tasks after a role.

### ISSUE THREAD

**Issue by benthomasson** [ansible/ansible-runner#107]
In the message data the role name is included for tasks after a role for roles in a play or include_role.

The `pause_for_kernel` task is not part of the `hello` role.  It was run after the hello role. 

Role was still set to `hello`:
```
                 u'role': u'hello',
```

Playbook:
```
- gather_facts: false
  hosts: localhost
  roles:
  - ansible_kernel_helpers
  - hello
  tasks:
  - pause_for_kernel:
      host: 127.0.0.1
      port: 50675
      task_num: 0
  - include_tasks: next_task1.yml
```

Message:

```
{'counter': 23,
 u'created': u'2018-08-06T20:02:58.849839',
 'end_line': 31,
 u'event': u'playbook_on_task_start',
 u'event_data': {u'is_conditional': False,
                 u'name': u'pause_for_kernel',
                 u'pid': 77031,
                 u'play': u'localhost',
                 u'play_pattern': u'localhost',
                 u'play_uuid': u'9801a79a-dd33-c9e6-7a97-000000000006',
                 u'playbook': u'playbook.yml',
                 u'playbook_uuid': u'44730e6f-e077-4ad0-bd00-a819c7fcaaf8',
                 u'role': u'hello',
                 u'task': u'pause_for_kernel',
                 u'task_action': u'pause_for_kernel',
                 u'task_args': u'task_num=1, host=127.0.0.1, port=50675',
                 u'task_path': u'/private/var/folders/p8/mttm7w913kq_v0wyfl9khlpc0000gn/T/ansible_kernel_playbookXmz9Pj/project/next_task1.yml:4',
                 u'task_uuid': u'9801a79a-dd33-c9e6-7a97-00000000002c'},
```
