### ISSUE TITLE
use of async wait tasks working in 2.10 break in 2.12

### ISSUE THREAD

**Issue by Chaffelson** [ansible/ansible-runner#1140]
We have several tasks which use async & poll0 to launch a bunch of slow object creations in parallel, and then track completion using async_status.

In 2.10 this works as expected, however in the 2.12 runner we see that the results file is looked for in the wrong path.

Example Tasks:
```
- name: Create Additional CDP DW Database catalogs
  when: not __dw_dbc_config.use_default_dbc
  cloudera.cloud.dw_database_catalog:
    cluster_id : "{{ __dw_cluster_id }}"
    name: "{{ __dw_dbc_config.name }}"
    load_demo_data: "{{ __dw_dbc_config.load_demo_data }}"
    state: present
    wait: yes
  async: 3600 # 1 hour timeout
  poll: 0
  loop: "{{ run__dw_dbc_configs }}"
  loop_control:
    loop_var: __dw_dbc_config
    label: "{{ __dw_dbc_config.name }}"
  register: __dw_dbc_builds

- name: Wait for additional CDP DW Database catalogs setup to complete
  when: __dw_dbc_build.ansible_job_id is defined
  ansible.builtin.async_status:
    jid: "{{ __dw_dbc_build.ansible_job_id }}"
  register: __dw_dbc_builds_async
  until: __dw_dbc_builds_async.finished
  retries: 120
  delay: 30
  loop: "{{ __dw_dbc_builds.results }}"
  loop_control:
    loop_var: __dw_dbc_build
    label: "{{ __dw_dbc_build.__dw_dbc_config.name }}"
```

Here is an example error:
```
failed: [localhost] (item=cmp-dbc) => {"__dw_dbc_build": {"__dw_dbc_config": {"load_demo_data": true, "name": "cmp-dbc", "use_default_dbc": false, "virtual_warehouses": [{"autoscaling": {"max_nodes": 3, "min_nodes": 1}, "name": "cmp-imp", "template": "xsmall", "type": "impala"}, {"autoscaling": {"max_nodes": 3, "min_nodes": 1}, "name": "cmp-hive-3", "type": "hive"}]}, "ansible_job_id": "20140938672.86392", "ansible_loop_var": "__dw_dbc_config", "changed": true, "failed": 0, "finished": 0, "results_file": "/home/runner/.ansible_async/20140938672.86392", "started": 1}, "ansible_job_id": "20140938672.86392", "ansible_loop_var": "__dw_dbc_build", "attempts": 1, "changed": false, "finished": 1, "msg": "could not find job", "results_file": "/root/.ansible_async/20140938672.86392", "started": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```
Note that it is looking in /root/.ansible_async (which does not exist) instead of in /home/runner/.ansible_async as it should. The Task and Play do not use become.
I have found an upstream issue that looks similar: [72207](https://github.com/ansible/ansible/issues/72207) , however this occurs whether inventory is forced to python3 or not.
