### ISSUE TITLE
Failed to authenticate: Authentication failed.

### ISSUE THREAD

**Issue by z3tsubouou** [ansible/ansible-runner#1299]
I am using ansible_runner.run() command and everything works except I can not connect to the server. Because password is wrong. How I am gonna use some_password inside of env/password when running ansible-runner?

playbook.yaml
```
-   name: Server
    hosts: "{{ host }}"
    gather_facts: false
    tasks:
        -   name: Docker container list
            shell: docker ps --format "{{ '{{' }}.ID{{ '}}' }}:{{ '{{' }}.Status{{ '}}' }}:{{ '{{' }}.Names{{ '}}' }}"
            register: result
    vars:
        ansible_user: "{{ host_user }}"
```
env/password
```
---
"Password:\\s*?$": "some_password"
```
app.py
```
    r = ansible_runner.run(
        private_data_dir="ansible",
        playbook="docker-container-list-playbook.yaml",
        extravars={
            "host": "host",
            "host_user": "user",
        }
    )
    print("{}: {}".format(r.status, r.rc))
```
