### ISSUE TITLE
Question - Command/Shell module stdout logged

### ISSUE THREAD

**Issue by debow77** [ansible/ansible-runner#1349]
I've noticed with ansible-runner that it appears to display command/shell module stdout to the screen by default but if I run ansible-playbook only it doesn't. Is there a way or something to suppress that without having to add `no_log: true` to those tasks? Just trying to understand why ansible-runner is displaying this and ansible-playbook doesn't.

Ansible version - 2.16.3
Ansible Runner - 2.3.4

**Comment by sivel** [comment]
You are likely going to need to provide more information, like what command you are running, the playbook, and the output.  I cannot reproduce with this simple reproducer:

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - command: whoami
```

```
$ ansible-runner run -p playbooks/playbook.yml pdd
PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by debow77** [comment]
One example of the task is...

```
    - name: Get active cert info
      ansible.builtin.shell:
        set -o pipefail && echo | openssl s_client -servername {{ item }} -connect {{ item }}:{{ websphere_odr_port }} -showcerts  2>/dev/null | openssl x509 -noout -subject -dates -fingerprint -issuer
      register: cur_certs_info
      changed_when: true
      loop:
        - "{{ dmgr_node }}"
        - "{{ sec_dmgr_node }}"
```

The output when running just ansible-playbook is
```
TASK [Get active cert info] **************************************************************************************************************************************************************************************************************************************************
changed: [node1.domain.com] => (item=node1.domain.com)
changed: [node1.domain.com] => (item=node2.domain.com)
```

The output when running with ansible-runner

```
TASK [Get active cert info] ****************************************************
changed: [node1.domain.com] => (item=node1.domain.com)subject= /C=US/ST=State/L=City/O=Company/CN=node1.domain.com
notBefore=Mar  1 18:56:36 2024 GMT
notAfter=Mar  1 18:56:36 2025 GMT
SHA1 Fingerprint=F8:34:0E:98:06:A7:87:C9:32:12:86:2D:40:EF:04:FC:B0:F2:C7:4F
issuer= /C=US/ST=State/L=City/O=Company/CN=Issuing 29
changed: [node1.domain.com] => (item=node2.domain.com)subject= /C=US/ST=State/L=City/O=Company/CN=node2.domain.com
notBefore=Mar  1 18:56:39 2024 GMT
notAfter=Mar  1 18:56:39 2025 GMT
SHA1 Fingerprint=A3:33:4A:BF:67:6E:A0:59:78:54:39:E9:BE:8D:73:64:2D:2D:53:80
issuer= /C=US/ST=State/L=City/O=Company/CN=Issuing 29
```
