### ISSUE TITLE
Duplicate output

### ISSUE THREAD

**Issue by Nani-o** [ansible/ansible-runner#182]
Using the latest 1.2.0 version, I have some problems trying to use ansible-runner.

I can only reproduce this problem on my Ubuntu server, on my OS X machine this works fine.

python : 3
ansible-runner : 1.2.0
ansible : 2.7.5

Given this simple playbook :
```YAML
---
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: ok
    - debug:
        msg: ko
```

I expect to see this (output from ansible-playbook command) : 
```SHELL
$ ansible-playbook toto.yml
 
PLAY [localhost] ***************************************************************************************************************************************

TASK [debug] *******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************************************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

Using ansible-runner this is what I get using it as a library : 
```SHELL
$ python3 toto.py

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}
ok: [localhost] => {
    "msg": "ko"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

And using it as a command line : 
```SHELL
$ ansible-runner run . -p toto.yml
 
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}
localhost                  : ok=2    changed=0    unreachable=0    failed=0



PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

When doing the same from my mac, everything works fine (python3 also on my mac).

**Comment by Nani-o** [comment]
I don't fully understand everything in the source code, but I came to the conclusion that removing [thoses lines](https://github.com/ansible/ansible-runner/blob/4a5a1d79104e3b14168b2d6aef1642f07a053ce0/ansible_runner/utils.py#L247-L251) solves my problem.

I am not sure about : 
  1. Why this is not an issue on OS X.
  2. Why this issue is inconsistent on Ubuntu (I just discovered searching for a solution that multiples runs produces extra output, but not the same everytime).

**Comment by matburt** [comment]
Rather than just removing the lines, we should look to see what the root cause is and why in certain scenarios we get the right output and duplicate lines otherwise.

I suspect this comes down to what's being flushed out to the stdout file versus the display as we're trying to do event payload + stdout joining.

**Comment by Nani-o** [comment]
Hi,

I was pretty sure it was not the fix, I just don't understand what the code trying to accomplish and why this happens. I was just trying to give all the informations I have gathered to help sort this out.

I can help reproduce and test this.

**Comment by chrismeyersfsu** [comment]
@Nani-o can you retry to recreate using the master branch of runner? A good bit of fixes have gone in recently.

**Comment by Nani-o** [comment]
@chrismeyersfsu The problem seems to be still here.

I installed it using `sudo -H pip3 install git+https://github.com/ansible/ansible-runner@master`. As I said previously, the duplicate output is not always the same, here two consecutive run using the master version : 

```YAML
$ ansible-runner run . -p toto.yml

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

```YAML
$ ansible-runner run . -p toto.yml

PLAY [localhost] ***************************************************************
ok: [localhost] => {
    "msg": "ok"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ok"
}
ok: [localhost] => {
    "msg": "ko"
}


TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "ko"
}
localhost                  : ok=2    changed=0    unreachable=0    failed=0



PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
