### ISSUE TITLE
fatal: [db01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to db01 closed.\r\n", "module_stdout"

### ISSUE THREAD

**Issue by hwali** [ansible/ansible-runner#199]
##### SUMMARY

I have an issue creating user over Ansible using python connecting DB,Please if someone cant support over this .yml,.py &,wsgi code pasted below
Got below error
TASK [create demo user] **********************************************************************************************************
fatal: [db01]: FAILED! => {"changed": false, "module_stderr": "Shared connection to db01 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_BpAAVO/ansible_module_mysql_user.py\", line 218, in <module>\r\n    from ansible.module_utils.basic import AnsibleModule\r\nzlib.error: Error -2 while preparing to decompress data: inconsistent stream state\r\n", "msg": "MODULE FAILURE", "rc": 0}
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

mysql_user, create demo user in mysql
##### ANSIBLE VERSION

```
[root@osboxes9 ~]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

```

##### CONFIGURATION

```
[defaults]
inventory = ./dev
++++
dev file config as below
[loadbalancer]
lb01

[database]
db01

[webserver]
osboxes1
osboxes2

[control]
control1 ansible_connection=local
```

##### OS / ENVIRONMENT
[root@osboxes9 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core) 
[root@osboxes9 ~]# 

##### STEPS TO REPRODUCE

Controller as Ansible >>>loadbalancer as front end>>>2x1 Web-servers & 1x1 Database as back  end

```yaml
---
- hosts: db01
  tasks:
    - name: install dependencies tool
      yum: name={{item}} state=latest update_cache=yes
      with_items:
          - MySQL-python
          -  mysql-devel
          -  python-devel

    - name: install mysql-server
      yum: name=mysql-server state=installed update_cache=yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

```

##### EXPECTED RESULTS
$curl osboxes1/db
Database Connected from osboxes1!
$curl osboxes2/db
Database Connected from osboxes2!
$curl lb01/db
Database Connected from osboxes1!
$curl lb01/db
Database Connected from osboxes2!

##### ACTUAL RESULTS

```paste below

```
