### ISSUE TITLE
Cannot access variable of playbook defined with set_fact

### ISSUE THREAD

**Issue by sylock** [ansible/ansible-runner#431]
**Explanation**
During the execution of a playbook, I define a new fact with set_fact. After the playbook execution, in the python script that called it, I want to retrieve that variable content. When using get_fact_cache on the runner object, I don't find that value.

For me this is a showstopper for ansible-runner since my core need is to be able to retrieve facts, including the ones defined with set_fact from the python script for further processing and usage.

**Code sample**

The minimal python script that calls the minimal ansible script, and try to print a fact set by set_fact
```python
import ansible_runner
r = ansible_runner.run(private_data_dir='/tmp', playbook='test.yml')
print(r.get_fact_cache('localhost'))
```
The minimal ansible script

```yaml
---
#located in /tmp/project/test.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: this is a test
    - set_fact:
        my_var: test_var
```
