### ISSUE TITLE
Extra variables new line formatting

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-runner#438]
Hi @matburt,
found an issue with extra variables. When using `\n` in extra variable ansible interprets it as space instead of the new line and `\\n` is a new line.
I was trying to debug it as much as possible but ended up on `pexpect`.

ansible-runner version: python3-ansible-runner-1.4.5-1

## Steps to reproduce it:
**Create playbook test.yml**
```yaml
- name: test
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Test
      copy:
        content: "{{ resp }}"
        dest: "/tmp/testfile"
```

With ansible-runner-service:
```
curl https://127.0.0.1:50001/api/v1/playbooks/test.yml \
--insecure \
-H "Content-Type: application/json" \
-d '{"resp":"test0\ntest1\\ntest2"}'
```

With python:
```python
command = ['ssh-agent', 'sh', '-c', 'ansible-playbook -e \'{"resp":"test0\\ntest1\ntest2"}\' test.yml']
pexpect.spawn(command[0], command[1:], encoding='utf-8').expect("ansible") 
```
result in the file
```
test0
test1 test2
```

## Suggested workaround:
https://github.com/ansible/ansible-runner/blob/devel/ansible_runner/runner_config.py#L402
add `.replace("\n","\\n")`
