### ISSUE TITLE
 Arbitrary role for tasks directly from playbook with host_pinned strategy

### ISSUE THREAD

**Issue by jplitza** [ansible/ansible-runner#587]
When executing a playbook with `strategy: host_pinned` (not sure if necessary, but probably is), the "role" attribute of tasks sitting directly in the playbook may be populated with seemingly arbitrary other roles that are included in the playbook.

To reproduce, run a playbook like the following on dozens of hosts
```yaml
- hosts:  all
  serial:
  - 1
  - 10
  strategy: host_pinned
  pre_tasks:
  - name: Pre-Task
    meta: noop
  roles:
  - myrole
  post_tasks:
  - name: Post-Task
    meta: noop
```
All of Pre-Task, Post-Task and even Gathering Facts sometimes have their role set to "myrole".

##### Speculation of the cause
Since most of the time they correctly have an empty role, this sounds like a concurrency issue. I didn't fully dive into the code, but maybe this is caused by the task being "global" in the output plugin "unless the free strategy is used"? Maybe host_pinned should also be an exception here?
https://github.com/ansible/ansible-runner/blob/58e0f1e0107b3ed6bfc0af4e613adfffffb9bd2f/ansible_runner/display_callback/module.py#L133

##### Context
I came here from ansible/awx#8810 since I encountered this issue while using AWX.
