### ISSUE TITLE
Extravars breaks some values

### ISSUE THREAD

**Issue by Ladas** [ansible/ansible-runner#62]
Having extra vars file 
```yaml
count: '2'
image_uuid: ami-a4dc46db
instance_indexed_tags: |-
  Name: ladas_ansible_test_2
  TestTag: test2
  TestTag2: test2
instance_name: ladas_ansible_test_2
instance_tags: |-
  Name: ladas_ansible_test_2
  TestTag: test2
instance_type: t2.nano
key_pair: ladas_ansible
region: us-east-1
security_group_description: ladas_ansible_test_1_sc_description
security_group_id: ''
security_group_name: ladas_ansible_test_1_sc_name
security_group_rules: |-
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: 0.0.0.0/0
security_group_rules_egress: |-
  - proto: all
    cidr_ip: 0.0.0.0/0
vpc_id: vpc-ff49ff91
vpc_subnet_id: subnet-5f5a9670
```

Ansible runner passes ```security_group_rules: "-"``` into my playbook. Similar behavior is if security_group_rules is a nested array.

Expecting this to work like ansible-playbook, where I can pass nested array or multiline string.
