### ISSUE TITLE
Ansible Var Prompt is not substuting the value with env/passwords

### ISSUE THREAD

**Issue by kameshsampath** [ansible/ansible-runner#653]
I am trying to use https://ansible-runner.readthedocs.io/en/stable/intro.html#env-passwords, with the password file like 

```
---
"Enter AWS Access Key:\\s*$": foo
"Enter AWS Secret Key:\\s*$": bar
```

My playbook is something like 

```yaml
- name: ROSA Fruits App Demo Setup
  hosts: localhost
  connection: local

  vars_prompt:
    - name: aws_access_key
      prompt: Enter AWS Access Key

    - name: aws_secret_key
      prompt: Enter AWS Secret Key

 tasks:
  - debug: msg="{{  aws_access_key }}"
```

I see the debug message printing it as "Hello World" . Is there anything wrong with my settings ??

I use Ansible Runner 1.4.7 and using ansible-builder container image to run the playbook via ansible-runner
